### ISSUE TITLE
[Improvement] Mirror the Gamepad sound effects

### ISSUE THREAD

**Issue by Sowden** [Fangal-Airbag/Better-Settings#1]
Hey there.  Thanks for making this plugin.  It has finally fixed the problem with the System Settings.  The only thing I'd ask for is an option to mirror, or swap the audio from the Gamepad to the TV.  That way we can hear the sound effects we've come to know and love.  Thanks for your work man, great stuff

**Comment by Fangal-Airbag** [comment]
Thank you for the kind words! So the reason I didn't do this is because [swipswapme](https://github.com/wiiu-env/SwipSwapMe) already does this way better then this plugin ever could and even allows for button combos to change the how the audio is played. I'd highly suggest using that. One thing that is unimplemented in this plugin is support for the stick buttons, which are the default button combo for the audio switch, so if that's something you'd want implemented I could certainly do that.

**Comment by Sowden** [comment]
Yeah dude, that would be great.  Thanks for all if your work!

**Comment by Fangal-Airbag** [comment]
Hey so I just checked and this already works out of the gate which is pretty neato. No need for any modifications, swipswapme just works. Thanks for letting me know about this though so I could test!
